import { BarcodeType } from '../plugins/barkoder';

export const barcodeTypeMap: Record<string, BarcodeType> = {
  aztec: BarcodeType.aztec,
  aztecCompact: BarcodeType.aztecCompact,
  qr: BarcodeType.qr,
  qrMicro: BarcodeType.qrMicro,
  code128: BarcodeType.code128,
  code93: BarcodeType.code93,
  code39: BarcodeType.code39,
  codabar: BarcodeType.codabar,
  code11: BarcodeType.code11,
  msi: BarcodeType.msi,
  upcA: BarcodeType.upcA,
  upcE: BarcodeType.upcE,
  upcE1: BarcodeType.upcE1,
  ean13: BarcodeType.ean13,
  ean8: BarcodeType.ean8,
  pdf417: BarcodeType.pdf417,
  pdf417Micro: BarcodeType.pdf417Micro,
  datamatrix: BarcodeType.datamatrix,
  code25: BarcodeType.code25,
  interleaved25: BarcodeType.interleaved25,
  itf14: BarcodeType.itf14,
  iata25: BarcodeType.iata25,
  matrix25: BarcodeType.matrix25,
  datalogic25: BarcodeType.datalogic25,
  coop25: BarcodeType.coop25,
  code32: BarcodeType.code32,
  telepen: BarcodeType.telepen,
  dotcode: BarcodeType.dotcode,
  idDocument: BarcodeType.idDocument,
  databar14: BarcodeType.databar14,
  databarLimited: BarcodeType.databarLimited,
  databarExpanded: BarcodeType.databarExpanded,
  postalIMB: BarcodeType.postalIMB,
  postnet: BarcodeType.postnet,
  planet: BarcodeType.planet,
  australianPost: BarcodeType.australianPost,
  royalMail: BarcodeType.royalMail,
  kix: BarcodeType.kix,
  japanesePost: BarcodeType.japanesePost,
  maxiCode: BarcodeType.maxiCode,
  ocrText: BarcodeType.ocrText,
};
